import ComputationalPaths.Path.Topology.ScopedGeometricRewriteGroupoid

/-!
# Challenge: topological semantics of computational paths

Prove `main_result`: the scoped geometric rewrite quotient of explicit,
endpoint-varying computational paths carries a canonical final-domain
topological groupoid.  The certificate records continuity of source, target,
identity, inverse, and composition, all unit and inverse laws, associativity,
and two concrete computational witnesses: trace-length composition and a
nontrivial rewrite of a composed reflexive trace.

The older final-domain/comparison interface below remains as supporting
notation for the extracted adapter, but is not the publication-facing claim.
-/

namespace TopologicalComputationalPaths

universe u v w

open ComputationalPaths.Path.GeometricTopology
open ComputationalPaths.Path.GeometricTopology.ScopedGeometricRewrite

/-! The publication-facing certificate keeps the concrete quotient groupoid
and its computational-path witnesses visible in the statement surface. -/

structure ScopedTopologicalComputationalPathCertificate
    {A : Type u} [TopologicalSpace A]
    {Step : Type v} [TopologicalSpace Step]
    (S : ContinuousGeometricStepSystem A Step)
    (P : ScopedGeometricRewritePresentation S) : Prop where
  source_continuous : Continuous (scopedSrc P)
  target_continuous : Continuous (scopedTgt P)
  identity_continuous : Continuous (scopedRefl P)
  inverse_continuous : Continuous (scopedSymm P)
  final_composition_continuous :
    Continuous (scopedCompositionOnStrong P :
      ScopedStrongComposablePair P → ScopedClass P)
  left_unit : ∀ p : ScopedClass P,
    scopedCompositionOnStrong P (strongLeftUnitPair P p) = p
  right_unit : ∀ p : ScopedClass P,
    scopedCompositionOnStrong P (strongRightUnitPair P p) = p
  right_inverse : ∀ p : ScopedClass P,
    scopedCompositionOnStrong P (strongRightInversePair P p) =
      scopedRefl P (scopedSrc P p)
  left_inverse : ∀ p : ScopedClass P,
    scopedCompositionOnStrong P (strongLeftInversePair P p) =
      scopedRefl P (scopedTgt P p)
  associativity : ∀ t : ScopedComposableTriple P,
    scopedCompositionOnStrong P (tripleLeftPair P t) =
      scopedCompositionOnStrong P (tripleRightPair P t)
  rewrite_sound :
    ∀ {p q : ScopedRawPath (S := S)},
      scopedEquivalent P p q →
        ∃ hs : q.src = p.src, ∃ ht : q.tgt = p.tgt,
          _root_.Path.Homotopic
            (GeometricTrace.realize (castScopedTrace hs ht))
            (GeometricTrace.realize q.trace)
  composition_trace_path : ∀ c : ScopedComposableRaw (S := S),
    Nonempty (ComputationalPaths.Path
      (GeometricTrace.traceLength
        (GeometricTrace.trans c.left.trace c.right.trace))
      (GeometricTrace.traceLength c.left.trace +
        GeometricTrace.traceLength c.right.trace))
  trace_unit_rewrite : ∀ p : ScopedRawPath (S := S),
    Nonempty (ComputationalPaths.Path.RwEq
      (ComputationalPaths.Path.trans
        (ComputationalPaths.Path.refl
          (GeometricTrace.traceLength p.trace))
        (ComputationalPaths.Path.refl
          (GeometricTrace.traceLength p.trace)))
      (ComputationalPaths.Path.refl (GeometricTrace.traceLength p.trace)))

/-! The final topology on a quotient is the coinduced topology generated by
the quotient map from its raw representatives. -/
noncomputable instance quotientFinalTopology
    {RawPair : Type u} [TopologicalSpace RawPair] (R : Setoid RawPair) :
    TopologicalSpace (Quotient R) :=
  TopologicalSpace.coinduced (Quotient.mk R) inferInstance

/-! `ScopedFinalPairData` is the statement-side abstraction of a quotient
of raw composable representatives.  The operation is supplied only on raw
representatives and must respect the rewrite relation; its final-domain
operation is defined canonically below. -/
structure ScopedFinalPairData
    (RawPair : Type u) (OrdinaryPair : Type v)
    (Arrow : Type w)
    [TopologicalSpace RawPair]
    [TopologicalSpace OrdinaryPair] [TopologicalSpace Arrow] where
  relation : Setoid RawPair
  comparison : Quotient relation ≃ OrdinaryPair
  rawOperation : RawPair → Arrow
  ordinaryOperation : OrdinaryPair → Arrow
  operation_respects :
    ∀ {r s : RawPair}, relation.r r s → rawOperation r = rawOperation s
  comparison_continuous : Continuous comparison
  rawOperation_continuous : Continuous rawOperation
  ordinary_factor : ∀ r,
    ordinaryOperation (comparison (Quotient.mk relation r)) = rawOperation r

namespace ScopedFinalPairData

variable {RawPair : Type u} {OrdinaryPair : Type v} {Arrow : Type w}
  [TopologicalSpace RawPair]
  [TopologicalSpace OrdinaryPair] [TopologicalSpace Arrow]
  (D : ScopedFinalPairData RawPair OrdinaryPair Arrow)

/-! The canonical quotient map into the final composable domain. -/
def quotient : RawPair → Quotient D.relation := Quotient.mk D.relation

/-! The raw operation descends because it respects the quotient relation. -/
noncomputable def finalOperation : Quotient D.relation → Arrow :=
  Quotient.lift D.rawOperation (by
    intro r s h
    exact D.operation_respects h)

theorem quotient_is_quotient : Topology.IsQuotientMap D.quotient := by
  exact ⟨⟨rfl⟩, Quotient.mk_surjective⟩

/-! The raw map into the ordinary pair space. -/
def pairMap : RawPair → OrdinaryPair := D.comparison ∘ D.quotient

/-! The ordinary topology is the topology induced by the comparison map. -/
def topologyAgreement : Prop :=
  (inferInstance : TopologicalSpace (Quotient D.relation)) =
    TopologicalSpace.induced D.comparison
      (inferInstance : TopologicalSpace OrdinaryPair)

end ScopedFinalPairData

/-! The topological and quotient-map consequences of the final-domain model. -/
structure ScopedFinalSemanticsCertificate
    {RawPair : Type u} {OrdinaryPair : Type v} {Arrow : Type w}
    [TopologicalSpace RawPair]
    [TopologicalSpace OrdinaryPair] [TopologicalSpace Arrow]
    (D : ScopedFinalPairData RawPair OrdinaryPair Arrow) : Prop where
  final_operation_continuous : Continuous D.finalOperation
  pair_map_quotient_iff_comparison_quotient :
    Topology.IsQuotientMap (D.pairMap) ↔
      Topology.IsQuotientMap D.comparison
  comparison_quotient_iff_inverse_continuous :
    Topology.IsQuotientMap D.comparison ↔
      Continuous D.comparison.invFun
  inverse_continuous_iff_topology_agreement :
    Continuous D.comparison.invFun ↔ D.topologyAgreement
  ordinary_operation_continuous_of_inverse :
    Continuous D.comparison.invFun → Continuous D.ordinaryOperation

/-! The generic comparison certificate remains available for downstream
adapter work, but the selected theorem below exposes the concrete
computational-path groupoid result. -/
theorem main_result
    {A : Type u} [TopologicalSpace A]
    {Step : Type v} [TopologicalSpace Step]
    (S : ContinuousGeometricStepSystem A Step)
    (P : ScopedGeometricRewritePresentation S) :
    ScopedTopologicalComputationalPathCertificate S P := by
  sorry

end TopologicalComputationalPaths
