import Mathlib.Topology.Constructions

/-!
# Challenge: final-domain topological semantics

Prove the certificate in `main_result`.  The data models a quotient of raw
composable representatives, its ordinary-pair comparison, and a descended
composition operation.  The result must distinguish unconditional continuity
on the final domain from continuity on the ordinary pullback domain.
-/

namespace TopologicalComputationalPaths

universe u v w

/-! The final topology on a quotient is the coinduced topology generated by
the quotient map from its raw representatives. -/
noncomputable instance quotientFinalTopology
    {RawPair : Type u} [TopologicalSpace RawPair] (R : Setoid RawPair) :
    TopologicalSpace (Quotient R) :=
  TopologicalSpace.coinduced (Quotient.mk R) inferInstance

/-! `ScopedFinalPairData` is the statement-side abstraction of a quotient
of raw composable representatives.  The operation is supplied only on raw
representatives and must respect the rewrite relation; its final-domain
operation is defined canonically below. -/
structure ScopedFinalPairData
    (RawPair : Type u) (OrdinaryPair : Type v)
    (Arrow : Type w)
    [TopologicalSpace RawPair]
    [TopologicalSpace OrdinaryPair] [TopologicalSpace Arrow] where
  relation : Setoid RawPair
  comparison : Quotient relation ≃ OrdinaryPair
  rawOperation : RawPair → Arrow
  ordinaryOperation : OrdinaryPair → Arrow
  operation_respects :
    ∀ {r s : RawPair}, relation.r r s → rawOperation r = rawOperation s
  comparison_continuous : Continuous comparison
  rawOperation_continuous : Continuous rawOperation
  ordinary_factor : ∀ r,
    ordinaryOperation (comparison (Quotient.mk relation r)) = rawOperation r

namespace ScopedFinalPairData

variable {RawPair : Type u} {OrdinaryPair : Type v} {Arrow : Type w}
  [TopologicalSpace RawPair]
  [TopologicalSpace OrdinaryPair] [TopologicalSpace Arrow]
  (D : ScopedFinalPairData RawPair OrdinaryPair Arrow)

/-! The canonical quotient map into the final composable domain. -/
def quotient : RawPair → Quotient D.relation := Quotient.mk D.relation

/-! The raw operation descends because it respects the quotient relation. -/
noncomputable def finalOperation : Quotient D.relation → Arrow :=
  Quotient.lift D.rawOperation (by
    intro r s h
    exact D.operation_respects h)

theorem quotient_is_quotient : Topology.IsQuotientMap D.quotient := by
  exact ⟨⟨rfl⟩, Quotient.mk_surjective⟩

/-! The raw map into the ordinary pair space. -/
def pairMap : RawPair → OrdinaryPair := D.comparison ∘ D.quotient

/-! The ordinary topology is the topology induced by the comparison map. -/
def topologyAgreement : Prop :=
  (inferInstance : TopologicalSpace (Quotient D.relation)) =
    TopologicalSpace.induced D.comparison
      (inferInstance : TopologicalSpace OrdinaryPair)

end ScopedFinalPairData

/-! The topological and quotient-map consequences of the final-domain model. -/
structure ScopedFinalSemanticsCertificate
    {RawPair : Type u} {OrdinaryPair : Type v} {Arrow : Type w}
    [TopologicalSpace RawPair]
    [TopologicalSpace OrdinaryPair] [TopologicalSpace Arrow]
    (D : ScopedFinalPairData RawPair OrdinaryPair Arrow) : Prop where
  final_operation_continuous : Continuous D.finalOperation
  pair_map_quotient_iff_comparison_quotient :
    Topology.IsQuotientMap (D.pairMap) ↔
      Topology.IsQuotientMap D.comparison
  comparison_quotient_iff_inverse_continuous :
    Topology.IsQuotientMap D.comparison ↔
      Continuous D.comparison.invFun
  inverse_continuous_iff_topology_agreement :
    Continuous D.comparison.invFun ↔ D.topologyAgreement
  ordinary_operation_continuous_of_inverse :
    Continuous D.comparison.invFun → Continuous D.ordinaryOperation

/-! Final-domain continuity is unconditional; ordinary-domain continuity is
available exactly through the inverse/comparison criterion recorded here. -/
theorem main_result
    {RawPair : Type u} {OrdinaryPair : Type v} {Arrow : Type w}
    [TopologicalSpace RawPair]
    [TopologicalSpace OrdinaryPair] [TopologicalSpace Arrow]
    (D : ScopedFinalPairData RawPair OrdinaryPair Arrow) :
    ScopedFinalSemanticsCertificate D := by
  sorry

end TopologicalComputationalPaths
