import ComputationalPaths.Path.Topology.CoherentRepresentativeElimination
import ComputationalPaths.Path.Topology.BinaryTimingCollision
import ComputationalPaths.Path.Topology.FlatEqualSlotRealization
import ComputationalPaths.Path.Topology.FlatObservableTopology
import ComputationalPaths.Path.Topology.ScopedWordInterpretation
import ComputationalPaths.Path.Topology.ContinuousWordInterpretation
import ComputationalPaths.Path.Topology.RedundantGeneratorObservable

/-! Kernel and axiom inspection for the first model-boundary milestone.
This file has no statement placeholders. Equal-slot observation on the tree
carrier is checked separately from literal composable-word correspondence.
The direct selected-declaration NanoDa replay has its own manifest; the five
earlier Comparator/NanoDa selections are checked separately in CI.
-/

#check ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.quotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.observableQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.traceSensitiveQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.realize_eq
#check ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.countC_invariant
#check ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.classes_ne
#check ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.not_t0
#check ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.fixed_not_t0

#print axioms ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.quotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.observableQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.traceSensitiveQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.realize_eq
#print axioms ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.countC_invariant
#print axioms ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.classes_ne
#print axioms ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.not_t0
#print axioms ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.fixed_not_t0

#check ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_slot
#check ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_eq_of_flatWord
#check ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_homotopic_binary
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.coherent_iff
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.scoped_sound
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.quotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.observableQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.traceSensitiveQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.continuous_totalQuotientMk

#print axioms ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_slot
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_eq_of_flatWord
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_homotopic_binary
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.coherent_iff
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.scoped_sound
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.quotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.observableQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.traceSensitiveQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.continuous_totalQuotientMk

#check ComputationalPaths.Path.GeometricTopology.WordSubstitution.realize_homotopic
#print axioms ComputationalPaths.Path.GeometricTopology.WordSubstitution.realize_homotopic
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.map_scoped
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.map_scoped
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.roundtrip
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.roundtrip
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.quotientEquiv
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.quotientEquiv
#check ComputationalPaths.Path.GeometricTopology.WordSubstitution.mapTrace_length
#print axioms ComputationalPaths.Path.GeometricTopology.WordSubstitution.mapTrace_length
#check ComputationalPaths.Path.GeometricTopology.WordSubstitution.mapTrace_realize
#print axioms ComputationalPaths.Path.GeometricTopology.WordSubstitution.mapTrace_realize
#check ComputationalPaths.Path.GeometricTopology.WordSubstitution.continuous_binary
#print axioms ComputationalPaths.Path.GeometricTopology.WordSubstitution.continuous_binary
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_quotientMap
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_quotientMap
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.quotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.quotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.binaryQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.binaryQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.quotientEquiv
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.quotientEquiv
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.old_parity_invariant
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.old_parity_invariant
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.continuous_oldParity
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.continuous_oldParity
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.old_parity_values
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.old_parity_values
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.countF_invariant
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.countF_invariant
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.new_classes_ne
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.new_classes_ne
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.new_inseparable
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.new_inseparable
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.not_continuous_inverse
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.not_continuous_inverse
