import ComputationalPaths.Path.Topology.ScopedWordInterpretation
import ComputationalPaths.Path.Topology.ContinuousWordInterpretation
import ComputationalPaths.Path.Topology.RedundantGeneratorObservable
import ComputationalPaths.Path.Topology.FlatEqualSlotRealization
import ComputationalPaths.Path.Topology.FlatObservableTopology
import ComputationalPaths.Path.Topology.CoherentRepresentativeElimination
import ComputationalPaths.Path.Topology.BinaryTimingCollision
import ComputationalPaths.Path.Topology.FlatWordContinuity
import ComputationalPaths.Path.Topology.LiteralWord
import ComputationalPaths.Path.Topology.LiteralWordRewrite
import ComputationalPaths.Path.Topology.LiteralWordQuotient
import ComputationalPaths.Path.Topology.LiteralWordGlobal
import ComputationalPaths.Path.Topology.LiteralWordPairs
import ComputationalPaths.Path.Topology.LiteralWordStrata
import ComputationalPaths.Path.Topology.LiteralWordTopologyBridge
import ComputationalPaths.Path.Topology.LiteralWordDiscrete
import ComputationalPaths.Path.Topology.FlatWordSubstitution
import ComputationalPaths.Path.Topology.VariableFlatWordInterpretation
import ComputationalPaths.Path.Topology.VariableFlatGlobalInterpretation
import ComputationalPaths.Path.Topology.RedundantGeneratorFlatSensitive
import ComputationalPaths.Path.Topology.FlatObservableDiscreteness
import ComputationalPaths.Path.Topology.CompleteDiscreteSeparation
import ComputationalPaths.Path.Topology.GeometricRose
import ComputationalPaths.Path.Topology.RoseReducedWords
import ComputationalPaths.Path.Topology.CayleyTreeGeometry
import ComputationalPaths.Path.Topology.CayleyRoseCovering
import ComputationalPaths.Path.Topology.RoseLiftedWords
import ComputationalPaths.Path.Topology.RoseBasedTopology
import ComputationalPaths.Path.Topology.CayleyReducedPrefix
import ComputationalPaths.Path.Topology.CayleyFlatWalk
import ComputationalPaths.Path.Topology.CayleyContraction
import ComputationalPaths.Path.Topology.RoseFundamentalGroup

#check ComputationalPaths.Path.GeometricTopology.WordSubstitution.realize_homotopic
#print axioms ComputationalPaths.Path.GeometricTopology.WordSubstitution.realize_homotopic
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.map_scoped
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.map_scoped
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.roundtrip
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.roundtrip
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.quotientEquiv
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.quotientEquiv
#check ComputationalPaths.Path.GeometricTopology.WordSubstitution.mapTrace_length
#print axioms ComputationalPaths.Path.GeometricTopology.WordSubstitution.mapTrace_length
#check ComputationalPaths.Path.GeometricTopology.WordSubstitution.mapTrace_realize
#print axioms ComputationalPaths.Path.GeometricTopology.WordSubstitution.mapTrace_realize
#check ComputationalPaths.Path.GeometricTopology.WordSubstitution.continuous_binary
#print axioms ComputationalPaths.Path.GeometricTopology.WordSubstitution.continuous_binary
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_quotientMap
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_quotientMap
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.quotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.quotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.binaryQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.binaryQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.quotientEquiv
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.quotientEquiv
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.old_parity_invariant
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.old_parity_invariant
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.continuous_oldParity
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.continuous_oldParity
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.old_parity_values
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.old_parity_values
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.countF_invariant
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.countF_invariant
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.new_classes_ne
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.new_classes_ne
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.new_inseparable
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.new_inseparable
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.not_continuous_inverse
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.not_continuous_inverse
#check ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_slot
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_slot
#check ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_eq_of_flatWord
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_eq_of_flatWord
#check ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_homotopic_binary
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricTrace.flatRealize_homotopic_binary
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.quotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.quotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.observableQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.observableQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.traceSensitiveQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.traceSensitiveQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.scoped_sound
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.scoped_sound
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.coherent_iff
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.coherent_iff
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.totalSensitiveTopology
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.totalSensitiveTopology
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.continuous_totalObservation
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.continuous_totalObservation
#check ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.continuous_totalQuotientMk
#print axioms ComputationalPaths.Path.GeometricTopology.EqualSlotTopology.continuous_totalQuotientMk
#check ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.quotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.quotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.observableQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.observableQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.traceSensitiveQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.CoherentRepresentativeElimination.traceSensitiveQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.realize_eq
#print axioms ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.realize_eq
#check ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.countC_invariant
#print axioms ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.countC_invariant
#check ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.classes_ne
#print axioms ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.classes_ne
#check ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.not_t0
#print axioms ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.not_t0
#check ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.fixed_not_t0
#print axioms ComputationalPaths.Path.GeometricTopology.BinaryTimingCollision.fixed_not_t0
#check ComputationalPaths.Path.GeometricTopology.weightedConcatenation_continuous_family
#print axioms ComputationalPaths.Path.GeometricTopology.weightedConcatenation_continuous_family
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.Word.ofTrace_toTrace
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.Word.ofTrace_toTrace
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.Word.toFlatWord_ofTrace
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.Word.toFlatWord_ofTrace
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.Word.normalization
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.Word.normalization
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.Word.scopedEq_of_flatWord
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.Word.scopedEq_of_flatWord
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.cancel_word
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.cancel_word
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.ofTrace_iff
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.ofTrace_iff
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.quotientEquiv
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.quotientEquiv
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.observableQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.observableQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.sensitiveQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.sensitiveQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.Strata.continuous_flatRealize_family
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.Strata.continuous_flatRealize_family
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.Strata.totalWordHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.Strata.totalWordHomeomorph
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.Strata.inducing_totalCode
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.Strata.inducing_totalCode
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.Strata.totalWordTopology_eq_induced_code
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.Strata.totalWordTopology_eq_induced_code
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.Strata.continuous_flatRealize_of_flatWord
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.Strata.continuous_flatRealize_of_flatWord
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.TotalWord.observableQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.TotalWord.observableQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.TotalWord.sensitiveQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.TotalWord.sensitiveQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.WordPair.observableQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.WordPair.observableQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.WordPair.sensitiveQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.WordPair.sensitiveQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.Word.sensitiveTopology_eq_tupleTopology
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.Word.sensitiveTopology_eq_tupleTopology
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.TotalWord.sensitiveTopology_eq_coproductTopology
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.TotalWord.sensitiveTopology_eq_coproductTopology
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.TotalWord.coproductHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.TotalWord.coproductHomeomorph
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.tupleQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.WordRwEq.tupleQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.TotalWord.coproductQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.TotalWord.coproductQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.WordPair.coproductQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.WordPair.coproductQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.discrete_wordQuotient
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.discrete_wordQuotient
#check ComputationalPaths.Path.GeometricTopology.LiteralWord.discrete_traceSensitiveQuotient
#print axioms ComputationalPaths.Path.GeometricTopology.LiteralWord.discrete_traceSensitiveQuotient
#check ComputationalPaths.Path.GeometricTopology.FlatWordSubstitution.continuous_bindTuple
#print axioms ComputationalPaths.Path.GeometricTopology.FlatWordSubstitution.continuous_bindTuple
#check ComputationalPaths.Path.GeometricTopology.FlatWordSubstitution.continuous_flatWordBind
#print axioms ComputationalPaths.Path.GeometricTopology.FlatWordSubstitution.continuous_flatWordBind
#check ComputationalPaths.Path.GeometricTopology.FlatWordSubstitution.continuous_signedImage
#print axioms ComputationalPaths.Path.GeometricTopology.FlatWordSubstitution.continuous_signedImage
#check ComputationalPaths.Path.GeometricTopology.FlatWordSubstitution.continuous_substitution
#print axioms ComputationalPaths.Path.GeometricTopology.FlatWordSubstitution.continuous_substitution
#check ComputationalPaths.Path.GeometricTopology.FlatWordSubstitution.mapTrace_flatWord
#print axioms ComputationalPaths.Path.GeometricTopology.FlatWordSubstitution.mapTrace_flatWord
#check ComputationalPaths.Path.GeometricTopology.WordSubstitution.continuous_flat_sensitive
#print axioms ComputationalPaths.Path.GeometricTopology.WordSubstitution.continuous_flat_sensitive
#check ComputationalPaths.Path.GeometricTopology.WordSubstitution.map_flat_homotopic
#print axioms ComputationalPaths.Path.GeometricTopology.WordSubstitution.map_flat_homotopic
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.flatSensitiveQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.flatSensitiveQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.discreteFlatSensitiveQuotientHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.discreteFlatSensitiveQuotientHomeomorph
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.mapRaw_equivalent
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.mapRaw_equivalent
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_flatSensitive_mapRaw
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_flatSensitive_mapRaw
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_flatSensitive_globalQuotientMap
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_flatSensitive_globalQuotientMap
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.flatSensitiveGlobalHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.flatSensitiveGlobalHomeomorph
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_flatSensitive_mapRawPair
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_flatSensitive_mapRawPair
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.finalPairMap_left
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.finalPairMap_left
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.finalPairMap_right
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.finalPairMap_right
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_flatSensitive_finalPairMap
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.continuous_flatSensitive_finalPairMap
#check ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.flatSensitiveFinalPairHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.ScopedWordInterpretation.flatSensitiveFinalPairHomeomorph
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.flatSensitiveHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.flatSensitiveHomeomorph
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.flatSensitiveGlobalHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.flatSensitiveGlobalHomeomorph
#check ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.flatSensitiveFinalPairHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.RedundantGeneratorObservable.flatSensitiveFinalPairHomeomorph
#check ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.flatWord_eq_of_observation
#print axioms ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.flatWord_eq_of_observation
#check ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.discrete_observable_words
#print axioms ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.discrete_observable_words
#check ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.discrete_observable_traceQuotient
#print axioms ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.discrete_observable_traceQuotient
#check ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.BinaryCircle.signedPrimitive_injective
#print axioms ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.BinaryCircle.signedPrimitive_injective
#check ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.BinaryCircle.flat_traceQuotient_discrete
#print axioms ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.BinaryCircle.flat_traceQuotient_discrete
#check ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.BinaryCircle.binary_flat_not_homeomorphic
#print axioms ComputationalPaths.Path.GeometricTopology.FlatObservableDiscreteness.BinaryCircle.binary_flat_not_homeomorphic
#check ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.complete
#print axioms ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.complete
#check ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.continuous_sectionTrace
#print axioms ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.continuous_sectionTrace
#check ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.observableHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.observableHomeomorph
#check ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.sensitive_discrete
#print axioms ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.sensitive_discrete
#check ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.inverse_not_continuous
#print axioms ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.inverse_not_continuous
#check ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.not_homeomorphic
#print axioms ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.not_homeomorphic
#check ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.coherentObservableHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.coherentObservableHomeomorph
#check ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.coherent_sensitive_discrete
#print axioms ComputationalPaths.Path.GeometricTopology.CompleteDiscreteSeparation.coherent_sensitive_discrete
#check ComputationalPaths.Path.GeometricTopology.GeometricRose.axesHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricRose.axesHomeomorph
#check ComputationalPaths.Path.GeometricTopology.GeometricRose.leftInclude_isEmbedding
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricRose.leftInclude_isEmbedding
#check ComputationalPaths.Path.GeometricTopology.GeometricRose.rightInclude_isEmbedding
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricRose.rightInclude_isEmbedding
#check ComputationalPaths.Path.GeometricTopology.GeometricRose.puncturedCircleHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricRose.puncturedCircleHomeomorph
#check ComputationalPaths.Path.GeometricTopology.GeometricRose.loopA
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricRose.loopA
#check ComputationalPaths.Path.GeometricTopology.GeometricRose.loopB
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricRose.loopB
#check ComputationalPaths.Path.GeometricTopology.GeometricRose.loopA_not_nullHomotopic
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricRose.loopA_not_nullHomotopic
#check ComputationalPaths.Path.GeometricTopology.GeometricRose.loopB_not_nullHomotopic
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricRose.loopB_not_nullHomotopic
#check ComputationalPaths.Path.GeometricTopology.GeometricRose.loopA_not_homotopic_loopB
#print axioms ComputationalPaths.Path.GeometricTopology.GeometricRose.loopA_not_homotopic_loopB
#check ComputationalPaths.Path.GeometricTopology.RoseReducedWords.normalization
#print axioms ComputationalPaths.Path.GeometricTopology.RoseReducedWords.normalization
#check ComputationalPaths.Path.GeometricTopology.RoseReducedWords.scoped_iff_encode_eq
#print axioms ComputationalPaths.Path.GeometricTopology.RoseReducedWords.scoped_iff_encode_eq
#check ComputationalPaths.Path.GeometricTopology.RoseReducedWords.quotientMulEquiv
#print axioms ComputationalPaths.Path.GeometricTopology.RoseReducedWords.quotientMulEquiv
#check ComputationalPaths.Path.GeometricTopology.RoseReducedWords.primitive_roundtrip
#print axioms ComputationalPaths.Path.GeometricTopology.RoseReducedWords.primitive_roundtrip
#check ComputationalPaths.Path.GeometricTopology.RoseReducedWords.ab_not_scoped_ba
#print axioms ComputationalPaths.Path.GeometricTopology.RoseReducedWords.ab_not_scoped_ba
#check ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.key_isQuotientMap
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.key_isQuotientMap
#check ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.edge
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.edge
#check ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.continuous_distanceFrom
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.continuous_distanceFrom
#check ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.distanceFrom_triangle
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.distanceFrom_triangle
#check ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.vertexNeighborhood_disjoint
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.vertexNeighborhood_disjoint
#check ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.isOpen_edgeInterior
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.isOpen_edgeInterior
#check ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.disjoint_translates
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyTreeGeometry.disjoint_translates
#check ComputationalPaths.Path.GeometricTopology.CayleyRoseCovering.project
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyRoseCovering.project
#check ComputationalPaths.Path.GeometricTopology.CayleyRoseCovering.project_isQuotientMap
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyRoseCovering.project_isQuotientMap
#check ComputationalPaths.Path.GeometricTopology.CayleyRoseCovering.project_eq_iff_mem_orbit
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyRoseCovering.project_eq_iff_mem_orbit
#check ComputationalPaths.Path.GeometricTopology.CayleyRoseCovering.covering
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyRoseCovering.covering
#check ComputationalPaths.Path.GeometricTopology.CayleyRoseCovering.project_edge
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyRoseCovering.project_edge
#check ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.liftWord
#print axioms ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.liftWord
#check ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.liftPath_trace_one
#print axioms ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.liftPath_trace_one
#check ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.trace_complete
#print axioms ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.trace_complete
#check ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.homotopic_iff_scoped
#print axioms ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.homotopic_iff_scoped
#check ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.ab_not_homotopic_ba
#print axioms ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.ab_not_homotopic_ba
#check ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.flat_trace_complete
#print axioms ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.flat_trace_complete
#check ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.flat_homotopic_iff_scoped
#print axioms ComputationalPaths.Path.GeometricTopology.RoseLiftedWords.flat_homotopic_iff_scoped
#check ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.windingPair_signedLoop
#print axioms ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.windingPair_signedLoop
#check ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.signedPrimitive_injective
#print axioms ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.signedPrimitive_injective
#check ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.flatObservable_discrete
#print axioms ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.flatObservable_discrete
#check ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.flatSensitive_discrete
#print axioms ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.flatSensitive_discrete
#check ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.flatObservableHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.flatObservableHomeomorph
#check ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.flatSensitiveHomeomorph
#print axioms ComputationalPaths.Path.GeometricTopology.RoseBasedTopology.flatSensitiveHomeomorph
#check ComputationalPaths.Path.GeometricTopology.CayleyReducedPrefix.toWord_mul_signed_cases
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyReducedPrefix.toWord_mul_signed_cases
#check ComputationalPaths.Path.GeometricTopology.CayleyReducedPrefix.outward_word_cases
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyReducedPrefix.outward_word_cases
#check ComputationalPaths.Path.GeometricTopology.CayleyReducedPrefix.toWord_prefix_cases
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyReducedPrefix.toWord_prefix_cases
#check ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.walkPath
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.walkPath
#check ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.rootPath
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.rootPath
#check ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.walkPath_append
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.walkPath_append
#check ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.walkPath_last_slot
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.walkPath_last_slot
#check ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.walkPath_prefix
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.walkPath_prefix
#check ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.outward_prefix
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.outward_prefix
#check ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.inward_prefix
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.inward_prefix
#check ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.outward_last_edge
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.outward_last_edge
#check ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.inward_last_edge
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyFlatWalk.inward_last_edge
#check ComputationalPaths.Path.GeometricTopology.CayleyContraction.contract
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyContraction.contract
#check ComputationalPaths.Path.GeometricTopology.CayleyContraction.homotopy
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyContraction.homotopy
#check ComputationalPaths.Path.GeometricTopology.CayleyContraction.edgeFormula_zero
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyContraction.edgeFormula_zero
#check ComputationalPaths.Path.GeometricTopology.CayleyContraction.edgeFormula_one
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyContraction.edgeFormula_one
#check ComputationalPaths.Path.GeometricTopology.CayleyContraction.contract_key
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyContraction.contract_key
#check ComputationalPaths.Path.GeometricTopology.CayleyContraction.continuous_contract
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyContraction.continuous_contract
#check ComputationalPaths.Path.GeometricTopology.CayleyContraction.contract_zero
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyContraction.contract_zero
#check ComputationalPaths.Path.GeometricTopology.CayleyContraction.contract_one
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyContraction.contract_one
#check ComputationalPaths.Path.GeometricTopology.CayleyContraction.contract_root
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyContraction.contract_root
#check ComputationalPaths.Path.GeometricTopology.CayleyContraction.contractible
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyContraction.contractible
#check ComputationalPaths.Path.GeometricTopology.CayleyContraction.simplyConnected
#print axioms ComputationalPaths.Path.GeometricTopology.CayleyContraction.simplyConnected
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.fundamentalGroupEquiv
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.fundamentalGroupEquiv
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.freeGroupEquiv
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.freeGroupEquiv
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loopWord
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loopWord
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.coherentRepresentative
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.coherentRepresentative
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.traceQuotientEquiv
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.traceQuotientEquiv
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.fundamentalGroupEquiv_realize
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.fundamentalGroupEquiv_realize
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.freeGroupEquiv_realize
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.freeGroupEquiv_realize
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loopWord_reduced
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loopWord_reduced
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loopWord_realize
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loopWord_realize
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loopWord_eq_iff_homotopic
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loopWord_eq_iff_homotopic
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loop_homotopic_decode
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loop_homotopic_decode
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loop_homotopic_flat_decode
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.loop_homotopic_flat_decode
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.every_loop_represented
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.every_loop_represented
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.coherentRepresentative_geometric
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.coherentRepresentative_geometric
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.traceQuotientEquiv_mk
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.traceQuotientEquiv_mk
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.traceQuotientEquiv_flat_mk
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.traceQuotientEquiv_flat_mk
#check ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.traceQuotientEquiv_mul
#print axioms ComputationalPaths.Path.GeometricTopology.RoseFundamentalGroup.traceQuotientEquiv_mul
