import ComputationalPaths.Path.Topology.CertifiedTorusPreimage
open ComputationalPaths.Path.GeometricTopology.CertifiedTorusPreimage
set_option maxRecDepth 100000
set_option maxHeartbeats 0

/- Generated by scripts/test-torus-preimage.py --lean.
   Every certificate and answer below is checked by Lean's kernel. -/

namespace Empty
def A : Mat 0 0 := ![]
def z : Vec 0 := ![]
def cert : Certificate 0 0 where
  L := ![]
  Linv := ![]
  R := ![]
  T := ![]
  d := ![]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![] := by decide
theorem answer : solve A cert z = .solved ![] := by
  have hf : cert.firstFailure z = none := by decide
  rw [solve, if_pos valid, hf]
  exact congrArg Outcome.solved (by decide : cert.candidate z = ![])
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.solved ![]) := by
  rw [← answer]
  exact topological_answer
end Empty

namespace NoConstraints
def A : Mat 0 3 := ![]
def z : Vec 0 := ![]
def cert : Certificate 0 3 where
  L := ![]
  Linv := ![]
  R := ![![], ![], ![]]
  T := ![]
  d := ![]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![![1, 0, 0], ![0, 1, 0], ![0, 0, 1]] := by decide
theorem answer : solve A cert z = .solved ![0, 0, 0] := by
  have hf : cert.firstFailure z = none := by decide
  rw [solve, if_pos valid, hf]
  exact congrArg Outcome.solved (by decide : cert.candidate z = ![0, 0, 0])
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.solved ![0, 0, 0]) := by
  rw [← answer]
  exact topological_answer
end NoConstraints

namespace NoVariablesYes
def A : Mat 2 0 := ![![], ![]]
def z : Vec 2 := ![0, 0]
def cert : Certificate 2 0 where
  L := ![![1, 0], ![0, 1]]
  Linv := ![![1, 0], ![0, 1]]
  R := ![]
  T := ![![], ![]]
  d := ![0, 0]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![] := by decide
theorem answer : solve A cert z = .solved ![] := by
  have hf : cert.firstFailure z = none := by decide
  rw [solve, if_pos valid, hf]
  exact congrArg Outcome.solved (by decide : cert.candidate z = ![])
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.solved ![]) := by
  rw [← answer]
  exact topological_answer
end NoVariablesYes

namespace NoVariablesNo
def A : Mat 2 0 := ![![], ![]]
def z : Vec 2 := ![0, 1]
def cert : Certificate 2 0 where
  L := ![![1, 0], ![0, 1]]
  Linv := ![![1, 0], ![0, 1]]
  R := ![]
  T := ![![], ![]]
  d := ![0, 0]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![] := by decide
theorem obstruction_data : cert.d (⟨1, by decide⟩ : Fin 2) = 0 ∧
    cert.transformed z (⟨1, by decide⟩ : Fin 2) = 1 ∧
    cert.L (⟨1, by decide⟩ : Fin 2) = ![0, 1] := by decide
theorem answer : solve A cert z = .obstructed ⟨1, by decide⟩ := by
  have hf : cert.firstFailure z = some ⟨1, by decide⟩ := by decide
  rw [solve, if_pos valid, hf]
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.obstructed ⟨1, by decide⟩) := by
  rw [← answer]
  exact topological_answer
end NoVariablesNo

namespace Divisible
def A : Mat 1 1 := ![![6]]
def z : Vec 1 := ![18]
def cert : Certificate 1 1 where
  L := ![![1]]
  Linv := ![![1]]
  R := ![![1]]
  T := ![![1]]
  d := ![6]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![![0]] := by decide
theorem answer : solve A cert z = .solved ![3] := by
  have hf : cert.firstFailure z = none := by decide
  rw [solve, if_pos valid, hf]
  exact congrArg Outcome.solved (by decide : cert.candidate z = ![3])
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.solved ![3]) := by
  rw [← answer]
  exact topological_answer
end Divisible

namespace TorsionObstruction
def A : Mat 1 1 := ![![6]]
def z : Vec 1 := ![17]
def cert : Certificate 1 1 where
  L := ![![1]]
  Linv := ![![1]]
  R := ![![1]]
  T := ![![1]]
  d := ![6]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![![0]] := by decide
theorem obstruction_data : cert.d (⟨0, by decide⟩ : Fin 1) = 6 ∧
    cert.transformed z (⟨0, by decide⟩ : Fin 1) = 17 ∧
    cert.L (⟨0, by decide⟩ : Fin 1) = ![1] := by decide
theorem answer : solve A cert z = .obstructed ⟨0, by decide⟩ := by
  have hf : cert.firstFailure z = some ⟨0, by decide⟩ := by decide
  rw [solve, if_pos valid, hf]
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.obstructed ⟨0, by decide⟩) := by
  rw [← answer]
  exact topological_answer
end TorsionObstruction

namespace NegativeFactor
def A : Mat 1 1 := ![![-6]]
def z : Vec 1 := ![18]
def cert : Certificate 1 1 where
  L := ![![-1]]
  Linv := ![![-1]]
  R := ![![1]]
  T := ![![1]]
  d := ![6]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![![0]] := by decide
theorem answer : solve A cert z = .solved ![-3] := by
  have hf : cert.firstFailure z = none := by decide
  rw [solve, if_pos valid, hf]
  exact congrArg Outcome.solved (by decide : cert.candidate z = ![-3])
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.solved ![-3]) := by
  rw [← answer]
  exact topological_answer
end NegativeFactor

namespace Wide
def A : Mat 2 3 := ![![2, 4, 0], ![0, 0, 3]]
def z : Vec 2 := ![6, 9]
def cert : Certificate 2 3 where
  L := ![![-1, 1], ![-3, 2]]
  Linv := ![![2, -1], ![3, -1]]
  R := ![![1, -3], ![0, 0], ![1, -2]]
  T := ![![-2, -4, 3], ![-1, -2, 1]]
  d := ![1, 6]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![![0, -2, 0], ![0, 1, 0], ![0, 0, 0]] := by decide
theorem answer : solve A cert z = .solved ![3, 0, 3] := by
  have hf : cert.firstFailure z = none := by decide
  rw [solve, if_pos valid, hf]
  exact congrArg Outcome.solved (by decide : cert.candidate z = ![3, 0, 3])
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.solved ![3, 0, 3]) := by
  rw [← answer]
  exact topological_answer
end Wide

namespace TallFreeObstruction
def A : Mat 3 2 := ![![2, 0], ![0, 3], ![2, 3]]
def z : Vec 3 := ![2, 3, 6]
def cert : Certificate 3 2 where
  L := ![![-1, 1, 0], ![-3, 2, 0], ![-1, -1, 1]]
  Linv := ![![2, -1, 0], ![3, -1, 0], ![5, -2, 1]]
  R := ![![1, -3, 0], ![1, -2, 0]]
  T := ![![-2, 3], ![-1, 1], ![0, 0]]
  d := ![1, 6, 0]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![![0, 0], ![0, 0]] := by decide
theorem obstruction_data : cert.d (⟨2, by decide⟩ : Fin 3) = 0 ∧
    cert.transformed z (⟨2, by decide⟩ : Fin 3) = 1 ∧
    cert.L (⟨2, by decide⟩ : Fin 3) = ![-1, -1, 1] := by decide
theorem answer : solve A cert z = .obstructed ⟨2, by decide⟩ := by
  have hf : cert.firstFailure z = some ⟨2, by decide⟩ := by decide
  rw [solve, if_pos valid, hf]
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.obstructed ⟨2, by decide⟩) := by
  rw [← answer]
  exact topological_answer
end TallFreeObstruction

namespace SingularYes
def A : Mat 2 2 := ![![2, 4], ![4, 8]]
def z : Vec 2 := ![6, 12]
def cert : Certificate 2 2 where
  L := ![![1, 0], ![-2, 1]]
  Linv := ![![1, 0], ![2, 1]]
  R := ![![1, 0], ![0, 0]]
  T := ![![1, 2], ![0, 0]]
  d := ![2, 0]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![![0, -2], ![0, 1]] := by decide
theorem answer : solve A cert z = .solved ![3, 0] := by
  have hf : cert.firstFailure z = none := by decide
  rw [solve, if_pos valid, hf]
  exact congrArg Outcome.solved (by decide : cert.candidate z = ![3, 0])
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.solved ![3, 0]) := by
  rw [← answer]
  exact topological_answer
end SingularYes

namespace SingularNo
def A : Mat 2 2 := ![![2, 4], ![4, 8]]
def z : Vec 2 := ![6, 13]
def cert : Certificate 2 2 where
  L := ![![1, 0], ![-2, 1]]
  Linv := ![![1, 0], ![2, 1]]
  R := ![![1, 0], ![0, 0]]
  T := ![![1, 2], ![0, 0]]
  d := ![2, 0]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![![0, -2], ![0, 1]] := by decide
theorem obstruction_data : cert.d (⟨1, by decide⟩ : Fin 2) = 0 ∧
    cert.transformed z (⟨1, by decide⟩ : Fin 2) = 1 ∧
    cert.L (⟨1, by decide⟩ : Fin 2) = ![-2, 1] := by decide
theorem answer : solve A cert z = .obstructed ⟨1, by decide⟩ := by
  have hf : cert.firstFailure z = some ⟨1, by decide⟩ := by decide
  rw [solve, if_pos valid, hf]
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.obstructed ⟨1, by decide⟩) := by
  rw [← answer]
  exact topological_answer
end SingularNo

namespace CoupledConstraints
def A : Mat 4 3 := ![![2, 4, 0], ![0, 3, 3], ![2, 7, 3], ![4, 8, 0]]
def z : Vec 4 := ![10, 15, 25, 20]
def cert : Certificate 4 3 where
  L := ![![-1, 1, 0, 0], ![-3, 2, 0, 0], ![-2, 0, 0, 1], ![-1, -1, 1, 0]]
  Linv := ![![2, -1, 0, 0], ![3, -1, 0, 0], ![5, -2, 0, 1], ![4, -2, 1, 0]]
  R := ![![-1, 1, 0, 0], ![1, -2, 0, 0], ![0, 0, 0, 0]]
  T := ![![-2, -1, 3], ![-1, -1, 1], ![0, 0, 0], ![0, 0, 0]]
  d := ![1, 6, 0, 0]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![![0, 0, 2], ![0, 0, -1], ![0, 0, 1]] := by decide
theorem answer : solve A cert z = .solved ![-5, 5, 0] := by
  have hf : cert.firstFailure z = none := by decide
  rw [solve, if_pos valid, hf]
  exact congrArg Outcome.solved (by decide : cert.candidate z = ![-5, 5, 0])
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.solved ![-5, 5, 0]) := by
  rw [← answer]
  exact topological_answer
end CoupledConstraints

namespace CoupledInconsistent
def A : Mat 4 3 := ![![2, 4, 0], ![0, 3, 3], ![2, 7, 3], ![4, 8, 0]]
def z : Vec 4 := ![10, 15, 26, 20]
def cert : Certificate 4 3 where
  L := ![![-1, 1, 0, 0], ![-3, 2, 0, 0], ![-2, 0, 0, 1], ![-1, -1, 1, 0]]
  Linv := ![![2, -1, 0, 0], ![3, -1, 0, 0], ![5, -2, 0, 1], ![4, -2, 1, 0]]
  R := ![![-1, 1, 0, 0], ![1, -2, 0, 0], ![0, 0, 0, 0]]
  T := ![![-2, -1, 3], ![-1, -1, 1], ![0, 0, 0], ![0, 0, 0]]
  d := ![1, 6, 0, 0]
theorem valid : cert.Valid A := by decide
theorem kernel_data : cert.kernelGenerator = ![![0, 0, 2], ![0, 0, -1], ![0, 0, 1]] := by decide
theorem obstruction_data : cert.d (⟨3, by decide⟩ : Fin 4) = 0 ∧
    cert.transformed z (⟨3, by decide⟩ : Fin 4) = 1 ∧
    cert.L (⟨3, by decide⟩ : Fin 4) = ![-1, -1, 1, 0] := by decide
theorem answer : solve A cert z = .obstructed ⟨3, by decide⟩ := by
  have hf : cert.firstFailure z = some ⟨3, by decide⟩ := by decide
  rw [solve, if_pos valid, hf]
theorem topological_answer : Torus.TopologicallyCorrect A cert z (solve A cert z) :=
  Torus.solve_topologically_correct A cert z
theorem checked_answer : Torus.TopologicallyCorrect A cert z (.obstructed ⟨3, by decide⟩) := by
  rw [← answer]
  exact topological_answer
end CoupledInconsistent
