/-
# Scoped completion quotients

A global rewrite relation can contain rules that are appropriate for one
syntactic construction but collapse distinctions in another.  This module
provides a reusable completion for loop presentations: choose an expression
type, a normal-form type, and mutually compatible encode/decode maps.  The
generated scoped step normalizes an expression to its canonical decoded normal
form.

The equivalence closure is proved sound and complete for equality of normal
forms.  Its quotient is therefore equivalent to the chosen normal-form type,
without importing unrelated global rewrite rules.

This is a completion interface, not a claim that normalization is derivable
from a smaller primitive presentation.  Each instance must expose and prove its
own `encode_decode` certificate.
-/

import ComputationalPaths.Path.Basic.Core
import ComputationalPaths.Path.Rewrite.RwEq
import ComputationalPaths.Path.Rewrite.SimpleEquiv

namespace ComputationalPaths
namespace Path
namespace ScopedCompletion

universe u v

/-- Data for a completed scoped loop presentation. -/
structure Data (Expr : Type u) (Normal : Type v) where
  /-- Compute the normal form of an expression. -/
  encode : Expr → Normal
  /-- Choose a canonical expression for each normal form. -/
  decode : Normal → Expr
  /-- Canonical expressions encode to their specified normal forms. -/
  encode_decode : ∀ n, encode (decode n) = n

variable {Expr : Type u} {Normal : Type v}

/-- The domain-specific completion step generated by `Data`. -/
inductive Step (P : Data Expr Normal) : Expr → Expr → Prop where
  | normalize (e : Expr) : Step P e (P.decode (P.encode e))

/-- Equivalence closure of the scoped completion step. -/
inductive RwEq (P : Data Expr Normal) : Expr → Expr → Prop where
  | refl (e : Expr) : RwEq P e e
  | step {e e' : Expr} : Step P e e' → RwEq P e e'
  | symm {e e' : Expr} : RwEq P e e' → RwEq P e' e
  | trans {e e' e'' : Expr} : RwEq P e e' → RwEq P e' e'' → RwEq P e e''

/-- A scoped completion step preserves normal forms. -/
theorem step_encode (P : Data Expr Normal)
    {e e' : Expr} (h : Step P e e') :
    P.encode e = P.encode e' := by
  cases h
  exact (P.encode_decode (P.encode e)).symm

/-- Every scoped rewrite derivation preserves normal forms. -/
theorem rweq_encode (P : Data Expr Normal)
    {e e' : Expr} (h : RwEq P e e') :
    P.encode e = P.encode e' := by
  induction h with
  | refl _ => rfl
  | step h => exact step_encode P h
  | symm _ ih => exact ih.symm
  | trans _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- Equal normal forms generate a scoped rewrite equivalence. -/
theorem rweq_of_encode_eq (P : Data Expr Normal)
    {e e' : Expr} (h : P.encode e = P.encode e') :
    RwEq P e e' := by
  have he : RwEq P e (P.decode (P.encode e)) :=
    RwEq.step (Step.normalize e)
  have he' : RwEq P e' (P.decode (P.encode e')) :=
    RwEq.step (Step.normalize e')
  rw [h] at he
  exact RwEq.trans he (RwEq.symm he')

/-- Exact classification of the generated scoped relation. -/
theorem rweq_iff_encode_eq (P : Data Expr Normal)
    {e e' : Expr} :
    RwEq P e e' ↔ P.encode e = P.encode e' :=
  ⟨rweq_encode P, rweq_of_encode_eq P⟩

/-- Setoid generated by a scoped completion. -/
noncomputable def setoid (P : Data Expr Normal) : Setoid Expr where
  r := RwEq P
  iseqv := by
    refine ⟨RwEq.refl, ?_, ?_⟩
    · intro e e' h
      exact RwEq.symm h
    · intro e e' e'' h₁ h₂
      exact RwEq.trans h₁ h₂

/-- Quotient of expressions by the generated scoped completion relation. -/
abbrev Quotient (P : Data Expr Normal) : Type u :=
  Quot (setoid P).r

/-- Encode a scoped quotient class. -/
noncomputable def encodeQuot (P : Data Expr Normal) :
    Quotient P → Normal :=
  Quot.lift P.encode (fun _ _ h => rweq_encode P h)

/-- Decode a normal form as its canonical scoped quotient class. -/
noncomputable def decodeQuot (P : Data Expr Normal) (n : Normal) :
    Quotient P :=
  Quot.mk _ (P.decode n)

@[simp] theorem encodeQuot_decodeQuot (P : Data Expr Normal) (n : Normal) :
    encodeQuot P (decodeQuot P n) = n :=
  P.encode_decode n

theorem decodeQuot_encodeQuot (P : Data Expr Normal) (x : Quotient P) :
    decodeQuot P (encodeQuot P x) = x := by
  induction x using Quot.ind with
  | _ e =>
      apply Quot.sound
      exact RwEq.symm (RwEq.step (.normalize e))

/-- The completed scoped quotient is equivalent to its normal-form type. -/
noncomputable def equivNormal (P : Data Expr Normal) :
    SimpleEquiv (Quotient P) Normal where
  toFun := encodeQuot P
  invFun := decodeQuot P
  left_inv := decodeQuot_encodeQuot P
  right_inv := encodeQuot_decodeQuot P

/-- Distinct normal forms yield distinct scoped quotient classes. -/
theorem decodeQuot_ne (P : Data Expr Normal) {n n' : Normal}
    (h : n ≠ n') :
    decodeQuot P n ≠ decodeQuot P n' := by
  intro classes_eq
  apply h
  simpa using _root_.congrArg (encodeQuot P) classes_eq

/-- Concrete Path certificate for soundness of the normalization step. -/
noncomputable def normalizationPath (P : Data Expr Normal) (e : Expr) :
    Path (P.encode e) (P.encode (P.decode (P.encode e))) :=
  Path.stepChain (step_encode P (Step.normalize e))

/-- The normalization certificate is coherent with right-unit composition. -/
noncomputable def normalizationCoherence (P : Data Expr Normal) (e : Expr) :
    _root_.ComputationalPaths.Path.RwEq
      (Path.trans (normalizationPath P e)
        (Path.refl (P.encode (P.decode (P.encode e)))))
      (normalizationPath P e) :=
  rweq_cmpA_refl_right (normalizationPath P e)

end ScopedCompletion
end Path
end ComputationalPaths
