import ComputationalPaths.Path.Topology.BasedScopedTraceGroup
import ComputationalPaths.Path.Topology.FiniteCircleTorusPresentation
import ComputationalPaths.Path.Topology.FiniteCircleTorusTraceSection

/-!
# Structural completeness of the one-generator circle presentation

The quotient group of based scoped traces is generated by the single circle
letter. This module derives finite-word normalization using only the structural
groupoid rewrites; the presentation has no named rewrite rule.
-/

namespace ComputationalPaths
namespace Path
namespace GeometricTopology
namespace FiniteCircleTorusPresentation

open BasedScopedTraceGroup
open ConcreteCircleWinding

private theorem windingPath_symm (γ : _root_.Path (0 : TopologicalCircle) 0) :
    windingPath γ.symm = -windingPath γ := by
  have h := windingPath_eq_of_homotopic (_root_.Path.Homotopic.trans_symm γ)
  rw [windingPath_trans, windingPath_refl] at h
  omega

theorem circleTraceEndpoints_eq
    {a b : TopologicalCircle}
    (p : GeometricTrace circleStepSystem.toGeometricStepSystem a b) :
    a = b := by
  induction p with
  | refl a => rfl
  | single g => simp [circleStepSystem]
  | trans p q ihp ihq => exact ihp.trans ihq
  | symm p ih => exact ih.symm

noncomputable def circleTraceCast
    {a b : TopologicalCircle}
    (ha : a = (0 : TopologicalCircle))
    (hb : b = (0 : TopologicalCircle))
    (p : GeometricTrace circleStepSystem.toGeometricStepSystem a b) :
    CircleTrace := by
  cases ha
  cases hb
  exact p

abbrev CircleScopedGroup :=
  BasedScopedTraceGroup.Carrier circleFinitePresentation (0 : TopologicalCircle)

noncomputable def circleGeneratorClass : CircleScopedGroup :=
  BasedScopedTraceGroup.mk circleFinitePresentation 0
    (.single CircleGenerator.a)

theorem circleClass_eq_zpow_aux
    {a b : TopologicalCircle}
    (p : GeometricTrace circleStepSystem.toGeometricStepSystem a b)
    (ha : a = (0 : TopologicalCircle))
    (hb : b = (0 : TopologicalCircle)) :
    BasedScopedTraceGroup.mk circleFinitePresentation 0
        (circleTraceCast ha hb p) =
      circleGeneratorClass ^ (circleExponent p) := by
  induction p with
  | refl a =>
      cases ha
      cases hb
      simp [circleTraceCast, circleExponent]
  | single g =>
      cases ha
      cases hb
      cases g
      simp [circleTraceCast, circleExponent, circleGeneratorClass]
  | trans p q ihp ihq =>
      have hmid : _ = (0 : TopologicalCircle) :=
        (circleTraceEndpoints_eq p).symm.trans ha
      cases ha
      cases hmid
      cases hb
      simp only [circleTraceCast, circleExponent, BasedScopedTraceGroup.mk_trans]
      have hp : BasedScopedTraceGroup.mk circleFinitePresentation 0 p =
          circleGeneratorClass ^ circleExponent p := by
        simpa [circleTraceCast] using ihp rfl rfl
      have hq : BasedScopedTraceGroup.mk circleFinitePresentation 0 q =
          circleGeneratorClass ^ circleExponent q := by
        simpa [circleTraceCast] using ihq rfl rfl
      rw [hp, hq, zpow_add]
  | symm p ih =>
      cases ha
      cases hb
      simp only [circleTraceCast, circleExponent, BasedScopedTraceGroup.mk_symm]
      have hp : BasedScopedTraceGroup.mk circleFinitePresentation 0 p =
          circleGeneratorClass ^ circleExponent p := by
        simpa [circleTraceCast] using ih rfl rfl
      rw [hp, zpow_neg]

theorem circleClass_eq_zpow (p : CircleTrace) :
    BasedScopedTraceGroup.mk circleFinitePresentation 0 p =
      circleGeneratorClass ^ (circleExponent p) :=
  circleClass_eq_zpow_aux p rfl rfl

theorem circleFinite_normalizes (p : CircleTrace) :
    ScopedRwEq circleFinitePresentation p
      (circleCanonical (circleExponent p)) := by
  apply (BasedScopedTraceGroup.eq_iff circleFinitePresentation 0 p
    (circleCanonical (circleExponent p))).1
  rw [circleClass_eq_zpow, circleClass_eq_zpow,
    circleExponent_canonical]

theorem circleExponent_realize_aux
    {a b : TopologicalCircle}
    (p : GeometricTrace circleStepSystem.toGeometricStepSystem a b)
    (ha : a = (0 : TopologicalCircle))
    (hb : b = (0 : TopologicalCircle)) :
    windingPath (GeometricTrace.realize (circleTraceCast ha hb p)) =
      circleExponent p := by
  induction p with
  | refl a =>
      cases ha
      cases hb
      change windingPath (_root_.Path.refl (0 : TopologicalCircle)) = 0
      exact windingPath_refl
  | single g =>
      cases ha
      cases hb
      cases g
      change windingPath (standardLoop 1) = 1
      exact windingPath_standardLoop 1
  | trans p q ihp ihq =>
      have hmid : _ = (0 : TopologicalCircle) :=
        (circleTraceEndpoints_eq p).symm.trans ha
      cases ha
      cases hmid
      cases hb
      simp only [circleTraceCast, GeometricTrace.realize, circleExponent]
      have hp : windingPath p.realize = circleExponent p := by
        simpa [circleTraceCast] using ihp rfl rfl
      have hq : windingPath q.realize = circleExponent q := by
        simpa [circleTraceCast] using ihq rfl rfl
      rw [windingPath_trans, hp, hq]
  | symm p ih =>
      cases ha
      cases hb
      simp only [circleTraceCast, GeometricTrace.realize, circleExponent]
      have hp : windingPath p.realize = circleExponent p := by
        simpa [circleTraceCast] using ih rfl rfl
      rw [windingPath_symm, hp]

theorem circleExponent_realize (p : CircleTrace) :
    windingPath (GeometricTrace.realize p) = circleExponent p :=
  circleExponent_realize_aux p rfl rfl

theorem circleFinite_trace_complete
    (p q : CircleTrace)
    (h : _root_.Path.Homotopic
      (GeometricTrace.realize p) (GeometricTrace.realize q)) :
    ScopedRwEq circleFinitePresentation p q := by
  have hcode : circleExponent p = circleExponent q := by
    rw [← circleExponent_realize, ← circleExponent_realize]
    exact windingPath_eq_of_homotopic h
  exact (ScopedRwEq.trans (circleFinite_normalizes p)
    (ScopedRwEq.trans
      (hcode ▸ ScopedRwEq.refl (circleCanonical (circleExponent p)))
      (ScopedRwEq.symm (circleFinite_normalizes q))))

theorem circleFinite_basedComplete
    (p q : FiniteCircleOpenLoop)
    (h : _root_.Path.Homotopic p.geometric q.geometric) :
    ScopedRwEq circleFinitePresentation p.trace q.trace := by
  exact circleFinite_trace_complete p.trace q.trace
    (p.coherent.symm.trans (h.trans q.coherent))

noncomputable def circleFiniteTraceHomeomorph :=
  finiteCircleTraceHomeomorph_of_complete circleFinitePresentation
    circleFinite_basedComplete

abbrev CircleFiniteBasedQuotient :=
  Quotient (finiteCircleBasedSetoid circleFinitePresentation)

noncomputable def circleFiniteWinding : CircleFiniteBasedQuotient → ℤ :=
  Quotient.lift (fun p : FiniteCircleOpenLoop => windingPath p.geometric)
    (by
      intro p q h
      apply windingPath_eq_of_homotopic
      exact p.coherent.trans ((ScopedRwEq.sound circleFinitePresentation h).trans
        q.coherent.symm))

noncomputable def circleFiniteWindingInverse (z : ℤ) :
    CircleFiniteBasedQuotient :=
  Quotient.mk (finiteCircleBasedSetoid circleFinitePresentation)
    (finiteCircleChosenTrace (standardLoop z))

theorem circleFiniteWinding_left_inv (q : CircleFiniteBasedQuotient) :
    circleFiniteWindingInverse (circleFiniteWinding q) = q := by
  refine Quotient.inductionOn q ?_
  intro p
  apply Quotient.sound
  apply circleFinite_basedComplete
  change _root_.Path.Homotopic
    (standardLoop (windingPath p.geometric)) p.geometric
  exact standardLoop_homotopic p.geometric

theorem circleFiniteWinding_right_inv (z : ℤ) :
    circleFiniteWinding (circleFiniteWindingInverse z) = z := by
  simp [circleFiniteWinding, circleFiniteWindingInverse,
    finiteCircleChosenTrace, windingPath_standardLoop]

noncomputable def circleFiniteWindingHomeomorph :
    @Homeomorph CircleFiniteBasedQuotient ℤ
      (TotalOpenGeometricCompPath.TraceSensitiveQuotient.quotientTopology
        (finiteCircleBasedSetoid circleFinitePresentation) inferInstance)
      inferInstance where
  toFun := circleFiniteWinding
  invFun := circleFiniteWindingInverse
  left_inv := circleFiniteWinding_left_inv
  right_inv := circleFiniteWinding_right_inv
  continuous_toFun := by
    apply Continuous.quotient_lift
    exact ConcreteCircleWinding.continuous_windingPath.comp
      (continuous_open_geometric circleStepSystem.toGeometricStepSystem)
  continuous_invFun := continuous_of_discreteTopology

end FiniteCircleTorusPresentation
end GeometricTopology
end Path
end ComputationalPaths
