import ComputationalPaths.Path.Topology.BasedScopedTraceGroup
import ComputationalPaths.Path.Topology.FiniteCircleTorusTraceSection

/-!
# The two-generator torus presentation

The finite scoped torus presentation has one named commuting square. The
structural groupoid laws supply inverses and cancellation. The based trace
quotient is generated by the two commuting classes, so every trace reduces
to its pair of signed exponents.
-/

namespace ComputationalPaths
namespace Path
namespace GeometricTopology
namespace FiniteCircleTorusPresentation

open BasedScopedTraceGroup

theorem torusTraceEndpoints_eq
    {a b : TorusCarrier}
    (p : GeometricTrace torusStepSystem.toGeometricStepSystem a b) :
    a = b := by
  induction p with
  | refl a => rfl
  | single g => cases g <;> simp [torusStepSystem]
  | trans p q ihp ihq => exact ihp.trans ihq
  | symm p ih => exact ih.symm

noncomputable def torusTraceCast
    {a b : TorusCarrier}
    (ha : a = torusBase) (hb : b = torusBase)
    (p : GeometricTrace torusStepSystem.toGeometricStepSystem a b) :
    TorusTrace := by
  cases ha
  cases hb
  exact p

abbrev TorusScopedGroup :=
  BasedScopedTraceGroup.Carrier torusFinitePresentation torusBase

noncomputable def torusAClass : TorusScopedGroup :=
  BasedScopedTraceGroup.mk torusFinitePresentation torusBase torusA

noncomputable def torusBClass : TorusScopedGroup :=
  BasedScopedTraceGroup.mk torusFinitePresentation torusBase torusB

theorem torusAB_commute : Commute torusAClass torusBClass := by
  change BasedScopedTraceGroup.mk torusFinitePresentation torusBase
      (.trans torusA torusB) =
    BasedScopedTraceGroup.mk torusFinitePresentation torusBase
      (.trans torusB torusA)
  apply Quotient.sound
  apply ScopedRwEq.generator
  exact ⟨rfl, rfl, rfl, rfl⟩

theorem torusNormal_mul (m n p q : ℤ) :
    (torusAClass ^ m * torusBClass ^ n) *
        (torusAClass ^ p * torusBClass ^ q) =
      torusAClass ^ (m + p) * torusBClass ^ (n + q) := by
  calc
    _ = torusAClass ^ m *
        (torusBClass ^ n * torusAClass ^ p) * torusBClass ^ q := by
          simp only [mul_assoc]
    _ = torusAClass ^ m *
        (torusAClass ^ p * torusBClass ^ n) * torusBClass ^ q := by
          rw [(torusAB_commute.zpow_zpow p n).symm.eq]
    _ = torusAClass ^ (m + p) * torusBClass ^ (n + q) := by
          rw [← mul_assoc, ← zpow_add, mul_assoc, ← zpow_add]

theorem torusNormal_inv (m n : ℤ) :
    (torusAClass ^ m * torusBClass ^ n)⁻¹ =
      torusAClass ^ (-m) * torusBClass ^ (-n) := by
  rw [mul_inv_rev, ← zpow_neg, ← zpow_neg]
  exact (torusAB_commute.zpow_zpow (-m) (-n)).symm.eq

theorem torusClass_eq_normal_aux
    {a b : TorusCarrier}
    (p : GeometricTrace torusStepSystem.toGeometricStepSystem a b)
    (ha : a = torusBase) (hb : b = torusBase) :
    BasedScopedTraceGroup.mk torusFinitePresentation torusBase
        (torusTraceCast ha hb p) =
      torusAClass ^ (torusCode p).1 * torusBClass ^ (torusCode p).2 := by
  induction p with
  | refl a =>
      cases ha
      cases hb
      simp [torusTraceCast, torusCode]
  | single g =>
      cases ha
      cases hb
      cases g <;> simp [torusTraceCast, torusCode, torusAClass,
        torusBClass, torusA, torusB]
  | trans p q ihp ihq =>
      have hmid : _ = torusBase :=
        (torusTraceEndpoints_eq p).symm.trans ha
      cases ha
      cases hmid
      cases hb
      simp only [torusTraceCast, torusCode, torusCodeAdd,
        BasedScopedTraceGroup.mk_trans]
      have hp : BasedScopedTraceGroup.mk torusFinitePresentation torusBase p =
          torusAClass ^ (torusCode p).1 * torusBClass ^ (torusCode p).2 := by
        simpa [torusTraceCast] using ihp rfl rfl
      have hq : BasedScopedTraceGroup.mk torusFinitePresentation torusBase q =
          torusAClass ^ (torusCode q).1 * torusBClass ^ (torusCode q).2 := by
        simpa [torusTraceCast] using ihq rfl rfl
      rw [hp, hq, torusNormal_mul]
  | symm p ih =>
      cases ha
      cases hb
      simp only [torusTraceCast, torusCode, torusCodeNeg,
        BasedScopedTraceGroup.mk_symm]
      have hp : BasedScopedTraceGroup.mk torusFinitePresentation torusBase p =
          torusAClass ^ (torusCode p).1 * torusBClass ^ (torusCode p).2 := by
        simpa [torusTraceCast] using ih rfl rfl
      rw [hp, torusNormal_inv]

theorem torusClass_eq_normal (p : TorusTrace) :
    BasedScopedTraceGroup.mk torusFinitePresentation torusBase p =
      torusAClass ^ (torusCode p).1 * torusBClass ^ (torusCode p).2 :=
  torusClass_eq_normal_aux p rfl rfl

theorem torusFinite_normalizes (p : TorusTrace) :
    ScopedRwEq torusFinitePresentation p (torusCanonical (torusCode p)) := by
  apply (BasedScopedTraceGroup.eq_iff torusFinitePresentation torusBase p
    (torusCanonical (torusCode p))).1
  rw [torusClass_eq_normal, torusClass_eq_normal, torusCode_canonical]

private theorem torusWinding_symm (γ : TopologicalTorus.Loop) :
    TopologicalTorus.winding γ.symm =
      (-(TopologicalTorus.winding γ).1,
        -(TopologicalTorus.winding γ).2) := by
  have h := TopologicalTorus.winding_eq_of_homotopic
    (_root_.Path.Homotopic.trans_symm γ)
  rw [TopologicalTorus.winding_trans, TopologicalTorus.winding_identity] at h
  apply Prod.ext <;> simp only [Prod.mk.injEq] at h ⊢
  · omega
  · omega

theorem torusCode_realize_aux
    {a b : TorusCarrier}
    (p : GeometricTrace torusStepSystem.toGeometricStepSystem a b)
    (ha : a = torusBase) (hb : b = torusBase) :
    TopologicalTorus.winding (GeometricTrace.realize
        (torusTraceCast ha hb p)) = torusCode p := by
  induction p with
  | refl a =>
      cases ha
      cases hb
      change TopologicalTorus.winding (_root_.Path.refl torusBase) = (0, 0)
      exact TopologicalTorus.winding_identity
  | single g =>
      cases ha
      cases hb
      cases g
      · change TopologicalTorus.winding
          (TopologicalTorus.firstFactorLoop 1) = (1, 0)
        exact TopologicalTorus.winding_firstFactorLoop 1
      · change TopologicalTorus.winding
          (TopologicalTorus.secondFactorLoop 1) = (0, 1)
        exact TopologicalTorus.winding_secondFactorLoop 1
  | trans p q ihp ihq =>
      have hmid : _ = torusBase :=
        (torusTraceEndpoints_eq p).symm.trans ha
      cases ha
      cases hmid
      cases hb
      simp only [torusTraceCast, GeometricTrace.realize, torusCode,
        torusCodeAdd]
      have hp : TopologicalTorus.winding p.realize = torusCode p := by
        simpa [torusTraceCast] using ihp rfl rfl
      have hq : TopologicalTorus.winding q.realize = torusCode q := by
        simpa [torusTraceCast] using ihq rfl rfl
      rw [TopologicalTorus.winding_trans, hp, hq]
  | symm p ih =>
      cases ha
      cases hb
      simp only [torusTraceCast, GeometricTrace.realize, torusCode,
        torusCodeNeg]
      have hp : TopologicalTorus.winding p.realize = torusCode p := by
        simpa [torusTraceCast] using ih rfl rfl
      rw [torusWinding_symm, hp]

theorem torusCode_realize (p : TorusTrace) :
    TopologicalTorus.winding (GeometricTrace.realize p) = torusCode p :=
  torusCode_realize_aux p rfl rfl

theorem torusFinite_trace_complete
    (p q : TorusTrace)
    (h : _root_.Path.Homotopic
      (GeometricTrace.realize p) (GeometricTrace.realize q)) :
    ScopedRwEq torusFinitePresentation p q := by
  have hcode : torusCode p = torusCode q := by
    rw [← torusCode_realize, ← torusCode_realize]
    exact TopologicalTorus.winding_eq_of_homotopic h
  exact ScopedRwEq.trans (torusFinite_normalizes p)
    (ScopedRwEq.trans
      (hcode ▸ ScopedRwEq.refl (torusCanonical (torusCode p)))
      (ScopedRwEq.symm (torusFinite_normalizes q)))

theorem torusFinite_basedComplete
    (p q : FiniteTorusOpenLoop)
    (h : _root_.Path.Homotopic p.geometric q.geometric) :
    ScopedRwEq torusFinitePresentation p.trace q.trace := by
  exact torusFinite_trace_complete p.trace q.trace
    (p.coherent.symm.trans (h.trans q.coherent))

noncomputable def torusFiniteTraceHomeomorph :=
  finiteTorusTraceHomeomorph_of_complete torusFinitePresentation
    torusFinite_basedComplete

abbrev TorusFiniteBasedQuotient :=
  Quotient (finiteTorusBasedSetoid torusFinitePresentation)

noncomputable def torusFiniteWinding :
    TorusFiniteBasedQuotient → ℤ × ℤ :=
  Quotient.lift (fun p : FiniteTorusOpenLoop => TopologicalTorus.winding p.geometric)
    (by
      intro p q h
      apply TopologicalTorus.winding_eq_of_homotopic
      exact p.coherent.trans ((ScopedRwEq.sound torusFinitePresentation h).trans
        q.coherent.symm))

noncomputable def torusFiniteWindingInverse (z : ℤ × ℤ) :
    TorusFiniteBasedQuotient :=
  Quotient.mk (finiteTorusBasedSetoid torusFinitePresentation)
    (finiteTorusChosenTrace (TopologicalTorus.standardLoop z.1 z.2))

theorem torusFiniteWinding_left_inv (q : TorusFiniteBasedQuotient) :
    torusFiniteWindingInverse (torusFiniteWinding q) = q := by
  refine Quotient.inductionOn q ?_
  intro p
  apply Quotient.sound
  apply torusFinite_basedComplete
  change _root_.Path.Homotopic
    (TopologicalTorus.standardLoop (TopologicalTorus.winding p.geometric).1
      (TopologicalTorus.winding p.geometric).2) p.geometric
  exact TopologicalTorus.standardLoop_homotopic p.geometric

theorem torusFiniteWinding_right_inv (z : ℤ × ℤ) :
    torusFiniteWinding (torusFiniteWindingInverse z) = z := by
  rcases z with ⟨m, n⟩
  simp [torusFiniteWinding, torusFiniteWindingInverse,
    finiteTorusChosenTrace, TopologicalTorus.winding_standardLoop]

noncomputable def torusFiniteWindingHomeomorph :
    @Homeomorph TorusFiniteBasedQuotient (ℤ × ℤ)
      (TotalOpenGeometricCompPath.TraceSensitiveQuotient.quotientTopology
        (finiteTorusBasedSetoid torusFinitePresentation) inferInstance)
      inferInstance where
  toFun := torusFiniteWinding
  invFun := torusFiniteWindingInverse
  left_inv := torusFiniteWinding_left_inv
  right_inv := torusFiniteWinding_right_inv
  continuous_toFun := by
    apply Continuous.quotient_lift
    exact TopologicalTorus.continuous_winding.comp
      (continuous_open_geometric torusStepSystem.toGeometricStepSystem)
  continuous_invFun := continuous_of_discreteTopology

end FiniteCircleTorusPresentation
end GeometricTopology
end Path
end ComputationalPaths
