import ComputationalPaths.Path.Topology.TotalCompPathHomotopyQuotient
import ComputationalPaths.Path.Topology.WeightedConcatenation
import ComputationalPaths.Path.Rewrite.RwEq

/-!
# Scoped geometric rewrite presentations

This file is the syntax/semantics core for the standalone topological paper.
The repository-wide `Path.RwEq` relation is intentionally not used to identify
these endpoint-changing geometric traces: it is a global relation on the raw
equality-indexed path type and would erase the distinctions that a presented
geometric rewrite system is meant to retain.

`ScopedGeometricRewritePresentation` supplies only domain-specific generators
and their geometric soundness witnesses.  `ScopedRwEq` then closes those
generators under the groupoid laws and congruence.  The resulting soundness
theorem is an induction over the complete scoped derivation, so later quotient
constructions can use it without importing an unproved semantic assumption.
-/

namespace ComputationalPaths
namespace Path
namespace GeometricTopology

open scoped ContinuousMap Topology

universe u v

/-! ## Presented generators -/

/-- A domain-specific family of geometric rewrite generators.

The endpoint-changing trace type is supplied by `S`.  A generator is required
to have a geometric endpoint-fixed homotopy witness; this is the only semantic
input needed for soundness of the generated rewrite equality.
-/
structure ScopedGeometricRewritePresentation
    {A : Type u} [TopologicalSpace A]
    {Step : Type v} [TopologicalSpace Step]
    (S : ContinuousGeometricStepSystem A Step) where
  rule : ∀ {a b : A},
    GeometricTrace S.toGeometricStepSystem a b →
      GeometricTrace S.toGeometricStepSystem a b → Prop
  sound_rule : ∀ {a b : A}
    {p q : GeometricTrace S.toGeometricStepSystem a b},
    rule p q →
      _root_.Path.Homotopic
        (GeometricTrace.realize p) (GeometricTrace.realize q)

/-! ## Scoped closure -/

/-- The equivalence congruence generated by the named presentation rules and
the strict groupoid coherence laws of geometric traces. -/
inductive ScopedRwEq
    {A : Type u} [TopologicalSpace A]
    {Step : Type v} [TopologicalSpace Step]
    {S : ContinuousGeometricStepSystem A Step}
    (P : ScopedGeometricRewritePresentation S) :
    {a b : A} →
      GeometricTrace S.toGeometricStepSystem a b →
        GeometricTrace S.toGeometricStepSystem a b → Prop
  | refl {a b : A}
      (p : GeometricTrace S.toGeometricStepSystem a b) :
      ScopedRwEq P p p
  | generator {a b : A}
      {p q : GeometricTrace S.toGeometricStepSystem a b} :
      P.rule p q → ScopedRwEq P p q
  | symm {a b : A}
      {p q : GeometricTrace S.toGeometricStepSystem a b} :
      ScopedRwEq P p q → ScopedRwEq P q p
  | trans {a b : A}
      {p q r : GeometricTrace S.toGeometricStepSystem a b} :
      ScopedRwEq P p q → ScopedRwEq P q r → ScopedRwEq P p r
  | trans_congr {a b c : A}
      {p p' : GeometricTrace S.toGeometricStepSystem a b}
      {q q' : GeometricTrace S.toGeometricStepSystem b c} :
      ScopedRwEq P p p' → ScopedRwEq P q q' →
        ScopedRwEq P
          (GeometricTrace.trans p q) (GeometricTrace.trans p' q')
  | symm_congr {a b : A}
      {p q : GeometricTrace S.toGeometricStepSystem a b} :
      ScopedRwEq P p q →
        ScopedRwEq P (GeometricTrace.symm p) (GeometricTrace.symm q)
  | refl_trans {a b : A}
      (p : GeometricTrace S.toGeometricStepSystem a b) :
      ScopedRwEq P
        (GeometricTrace.trans (GeometricTrace.refl a) p) p
  | trans_refl {a b : A}
      (p : GeometricTrace S.toGeometricStepSystem a b) :
      ScopedRwEq P
        (GeometricTrace.trans p (GeometricTrace.refl b)) p
  | trans_assoc {a b c d : A}
      (p : GeometricTrace S.toGeometricStepSystem a b)
      (q : GeometricTrace S.toGeometricStepSystem b c)
      (r : GeometricTrace S.toGeometricStepSystem c d) :
      ScopedRwEq P
        (GeometricTrace.trans (GeometricTrace.trans p q) r)
        (GeometricTrace.trans p (GeometricTrace.trans q r))
  | symm_trans {a b : A}
      (p : GeometricTrace S.toGeometricStepSystem a b) :
      ScopedRwEq P
        (GeometricTrace.trans (GeometricTrace.symm p) p)
        (GeometricTrace.refl b)
  | trans_symm {a b : A}
      (p : GeometricTrace S.toGeometricStepSystem a b) :
      ScopedRwEq P
        (GeometricTrace.trans p (GeometricTrace.symm p))
        (GeometricTrace.refl a)
  | symm_symm {a b : A}
      (p : GeometricTrace S.toGeometricStepSystem a b) :
      ScopedRwEq P
        (GeometricTrace.symm (GeometricTrace.symm p)) p
  | symm_refl (a : A) :
      ScopedRwEq P
        (GeometricTrace.symm (GeometricTrace.refl a))
        (GeometricTrace.refl a)
  | symm_comp {a b c : A}
      (p : GeometricTrace S.toGeometricStepSystem a b)
      (q : GeometricTrace S.toGeometricStepSystem b c) :
      ScopedRwEq P
        (GeometricTrace.symm (GeometricTrace.trans p q))
        (GeometricTrace.trans (GeometricTrace.symm q)
          (GeometricTrace.symm p))

namespace ScopedRwEq

variable {A : Type u} [TopologicalSpace A]
  {Step : Type v} [TopologicalSpace Step]
  {S : ContinuousGeometricStepSystem A Step}
  (P : ScopedGeometricRewritePresentation S)

/-- Every scoped rewrite derivation is sound for geometric realization. -/
theorem sound
    {a b : A}
    {p q : GeometricTrace S.toGeometricStepSystem a b}
    (h : ScopedRwEq P p q) :
    _root_.Path.Homotopic
      (GeometricTrace.realize p) (GeometricTrace.realize q) := by
  induction h with
  | refl p => exact ⟨_root_.Path.Homotopy.refl (GeometricTrace.realize p)⟩
  | generator h => exact P.sound_rule h
  | symm h ih =>
      rcases ih with ⟨ih⟩
      exact ⟨ih.symm⟩
  | trans h₁ h₂ ih₁ ih₂ =>
      rcases ih₁ with ⟨ih₁⟩
      rcases ih₂ with ⟨ih₂⟩
      exact ⟨ih₁.trans ih₂⟩
  | trans_congr h₁ h₂ ih₁ ih₂ =>
      rcases ih₁ with ⟨ih₁⟩
      rcases ih₂ with ⟨ih₂⟩
      exact ⟨ih₁.hcomp ih₂⟩
  | symm_congr h ih =>
      rcases ih with ⟨ih⟩
      exact ⟨ih.symm₂⟩
  | refl_trans p =>
      exact ⟨by simpa [GeometricTrace.realize] using
        (_root_.Path.Homotopy.reflTrans (GeometricTrace.realize p))⟩
  | trans_refl p =>
      exact ⟨by simpa [GeometricTrace.realize] using
        (_root_.Path.Homotopy.transRefl (GeometricTrace.realize p))⟩
  | trans_assoc p q r =>
      exact ⟨by simpa [GeometricTrace.realize] using
        (_root_.Path.Homotopy.transAssoc
          (GeometricTrace.realize p) (GeometricTrace.realize q)
          (GeometricTrace.realize r))⟩
  | symm_trans p =>
      exact ⟨by simpa [GeometricTrace.realize] using
        (_root_.Path.Homotopy.reflSymmTrans
          (GeometricTrace.realize p)).symm⟩
  | trans_symm p =>
      exact ⟨by simpa [GeometricTrace.realize] using
        (_root_.Path.Homotopy.reflTransSymm
          (GeometricTrace.realize p)).symm⟩
  | symm_symm p =>
      exact ⟨by simpa [GeometricTrace.realize] using
        (_root_.Path.Homotopy.refl (GeometricTrace.realize p))⟩
  | symm_refl a =>
      exact ⟨by simpa [GeometricTrace.realize] using
        (_root_.Path.Homotopy.refl (_root_.Path.refl a))⟩
  | symm_comp p q =>
      exact ⟨by simpa [GeometricTrace.realize] using
        (_root_.Path.Homotopy.refl
          (_root_.Path.trans (GeometricTrace.realize q).symm
            (GeometricTrace.realize p).symm))⟩

end ScopedRwEq

/-! ## Endpoint-varying raw carrier and its scoped setoid -/

/-- A raw endpoint-varying carrier retaining the coherent geometric witness.
The quotient relation below depends only on the trace, so the geometric witness
is forgotten exactly through the declared rewrite presentation. -/
abbrev ScopedRawPath
    {A : Type u} [TopologicalSpace A]
    {Step : Type v} [TopologicalSpace Step]
    {S : ContinuousGeometricStepSystem A Step} :=
  TotalOpenGeometricCompPath A Step S

noncomputable def castScopedTrace
    {A : Type u} [TopologicalSpace A]
    {Step : Type v} [TopologicalSpace Step]
    {S : ContinuousGeometricStepSystem A Step}
    {p q : ScopedRawPath (S := S)}
    (hs : q.src = p.src) (ht : q.tgt = p.tgt) :
    GeometricTrace S.toGeometricStepSystem q.src q.tgt := by
  exact ContinuousGeometricStepSystemMap.castTrace
    (S := S) hs ht p.trace

/-- Two raw paths are equivalent exactly when their endpoints agree and their
traces are related by the scoped presentation. -/
def scopedEquivalent
    {A : Type u} [TopologicalSpace A]
    {Step : Type v} [TopologicalSpace Step]
    {S : ContinuousGeometricStepSystem A Step}
    (P : ScopedGeometricRewritePresentation S)
    (p q : ScopedRawPath (S := S)) : Prop :=
  ∃ hs : q.src = p.src, ∃ ht : q.tgt = p.tgt,
    ScopedRwEq P (castScopedTrace hs ht) q.trace

noncomputable def scopedSetoid
    {A : Type u} [TopologicalSpace A]
    {Step : Type v} [TopologicalSpace Step]
    {S : ContinuousGeometricStepSystem A Step}
    (P : ScopedGeometricRewritePresentation S) :
    Setoid (ScopedRawPath (S := S)) where
  r := scopedEquivalent P
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro p
      exact ⟨rfl, rfl, ScopedRwEq.refl p.trace⟩
    · intro p q h
      rcases p with ⟨p_src, p_tgt, p_path⟩
      rcases q with ⟨q_src, q_tgt, q_path⟩
      rcases h with ⟨hs, ht, h⟩
      cases hs
      cases ht
      exact ⟨rfl, rfl, ScopedRwEq.symm h⟩
    · intro p q r h₁ h₂
      rcases p with ⟨p_src, p_tgt, p_path⟩
      rcases q with ⟨q_src, q_tgt, q_path⟩
      rcases r with ⟨r_src, r_tgt, r_path⟩
      rcases h₁ with ⟨hs₁, ht₁, h₁⟩
      rcases h₂ with ⟨hs₂, ht₂, h₂⟩
      cases hs₁
      cases ht₁
      cases hs₂
      cases ht₂
      exact ⟨rfl, rfl, ScopedRwEq.trans h₁ h₂⟩

abbrev ScopedClass
    {A : Type u} [TopologicalSpace A]
    {Step : Type v} [TopologicalSpace Step]
    {S : ContinuousGeometricStepSystem A Step}
    (P : ScopedGeometricRewritePresentation S) : Type _ :=
  Quotient (scopedSetoid P)

noncomputable def scopedQuotientMk
    {A : Type u} [TopologicalSpace A]
    {Step : Type v} [TopologicalSpace Step]
    {S : ContinuousGeometricStepSystem A Step}
    (P : ScopedGeometricRewritePresentation S)
    (p : ScopedRawPath (S := S)) : ScopedClass P :=
  Quotient.mk (scopedSetoid P) p

theorem scopedEquivalent_sound
    {A : Type u} [TopologicalSpace A]
    {Step : Type v} [TopologicalSpace Step]
    {S : ContinuousGeometricStepSystem A Step}
    (P : ScopedGeometricRewritePresentation S)
    {p q : ScopedRawPath (S := S)}
    (h : scopedEquivalent P p q) :
    ∃ hs : q.src = p.src, ∃ ht : q.tgt = p.tgt,
      _root_.Path.Homotopic
        (GeometricTrace.realize (castScopedTrace hs ht))
        (GeometricTrace.realize q.trace) := by
  exact h.imp fun hs hrest => hrest.imp fun ht hrewrite =>
    ScopedRwEq.sound P hrewrite

end GeometricTopology
end Path
end ComputationalPaths
