#!/usr/bin/env python3
"""Deterministic generator regression suite; --lean emits replayable examples.

The Python checks are supporting tests, not a replacement for Lean validation.
"""
import argparse
import importlib.util
import json
from pathlib import Path
import random
import sys
import time
import platform

sys.dont_write_bytecode = True

spec = importlib.util.spec_from_file_location(
    "producer", Path(__file__).with_name("torus-preimage-certificate.py"))
producer = importlib.util.module_from_spec(spec)
spec.loader.exec_module(producer)

CASES = [
    ("Empty", 0, 0, [], []),
    ("NoConstraints", 0, 3, [], []),
    ("NoVariablesYes", 2, 0, [[], []], [0, 0]),
    ("NoVariablesNo", 2, 0, [[], []], [0, 1]),
    ("Divisible", 1, 1, [[6]], [18]),
    ("TorsionObstruction", 1, 1, [[6]], [17]),
    ("NegativeFactor", 1, 1, [[-6]], [18]),
    ("Wide", 2, 3, [[2, 4, 0], [0, 0, 3]], [6, 9]),
    ("TallFreeObstruction", 3, 2, [[2, 0], [0, 3], [2, 3]], [2, 3, 6]),
    ("SingularYes", 2, 2, [[2, 4], [4, 8]], [6, 12]),
    ("SingularNo", 2, 2, [[2, 4], [4, 8]], [6, 13]),
    ("CoupledConstraints", 4, 3,
     [[2, 4, 0], [0, 3, 3], [2, 7, 3], [4, 8, 0]], [10, 15, 25, 20]),
    ("CoupledInconsistent", 4, 3,
     [[2, 4, 0], [0, 3, 3], [2, 7, 3], [4, 8, 0]], [10, 15, 26, 20]),
]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lean", action="store_true")
    parser.add_argument("--benchmark", action="store_true")
    args = parser.parse_args()
    records, snippets = [], []
    cases = CASES
    if args.benchmark:
        rng = random.Random(134)
        cases = []
        for index, (m, n) in enumerate([(3, 5), (5, 3), (6, 6), (8, 5), (5, 8)]):
            A = [[rng.randrange(-3, 4) for _ in range(n)] for _ in range(m)]
            if index % 2:
                A[-1] = [a + b for a, b in zip(A[0], A[1])]
            x = [rng.randrange(-10, 11) for _ in range(n)]
            z = [sum(a * b for a, b in zip(row, x)) for row in A]
            cases.append((f"Benchmark{m}x{n}", m, n, A, z))
    for name, m, n, A, z in cases:
        start = time.perf_counter()
        result = producer.generate({"rows": m, "cols": n, "matrix": A, "target": z})
        records.append({"name": name, "rows": m, "cols": n,
                        "producer_seconds": time.perf_counter() - start,
                        "certificate_json_bytes": len(json.dumps(result["certificate"]).encode()),
                        "outcome": result["outcome"]})
        snippets.append(producer.emit_lean(result, name))
    if args.lean:
        print("import ComputationalPaths.Path.Topology.CertifiedTorusPreimage\n"
              "open ComputationalPaths.Path.GeometricTopology.CertifiedTorusPreimage\n"
              "set_option maxRecDepth 100000\nset_option maxHeartbeats 0\n\n"
              f"/- Generated by scripts/test-torus-preimage.py --lean{' --benchmark' if args.benchmark else ''}.\n"
              "   Every certificate and answer below is checked by Lean's kernel. -/\n")
        print("\n\n".join(snippets))
        return
    rng = random.Random(742)
    spoofed = producer.generate({"rows": 1, "cols": 1, "matrix": [[1]], "target": [1],
                                 "verification": {"lean_kernel": "accepted"}})
    if "verification" in spoofed:
        raise AssertionError("untrusted input supplied a verification status")
    for malformed in [
        {"rows": True, "cols": 1, "matrix": [[1]], "target": [1]},
        {"rows": 1, "cols": 1, "matrix": [[1.5]], "target": [1]},
        {"rows": 1, "cols": 2, "matrix": [[1]], "target": [1]},
        {"rows": 1, "cols": 1, "matrix": [[1]], "target": [False]},
    ]:
        try:
            producer.generate(malformed)
        except ValueError:
            pass
        else:
            raise AssertionError("malformed input accepted")
    for trial in range(0 if args.benchmark else 100):
        m, n = rng.randrange(5), rng.randrange(5)
        A = [[rng.randrange(-8, 9) for _ in range(n)] for _ in range(m)]
        x = [rng.randrange(-5, 6) for _ in range(n)]
        z = [sum(a * b for a, b in zip(row, x)) for row in A]
        result = producer.generate({"rows": m, "cols": n, "matrix": A, "target": z})
        if "solved" not in result["outcome"]:
            raise AssertionError(f"generated image rejected in trial {trial}")
    print(json.dumps({"seed": 134 if args.benchmark else 742,
                      "known_image_trials": 0 if args.benchmark else 100,
                      "environment": {"platform": platform.platform(),
                                      "python": platform.python_version(),
                                      "sympy": producer.sympy_version},
                      "fixtures": records,
                      "timing_scope": "untrusted Python producer only; not Lean replay"}, indent=2))


if __name__ == "__main__":
    main()
